version: "3.8"

services:
  fn-express-api:
    build:
      context: "./server"
      dockerfile: Dockerfile
    container_name: fn-express-api
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo-db
    restart: always

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
